
spring:
  application:
    name: auth-service
  mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/auth_db}

server:
  port: 8081

jwt:
  secret: thisIsASecretKeyForJWTtokensThatWasMadeByMomoWithAnFathomaleAmountOfHate