spring:
  application:
    name: ${SPRING_APPLICATION_NAME:auth-service}
  docker:
    compose:
      enabled: false
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI}
  jwt:
    secret: ${JWT_SECRET:default_secret_key}
    expiration: ${JWT_EXPIRATION:86400000} # 24 hour in milliseconds
server:
  port: ${SERVER_PORT:8081}

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}