spring:
  docker:
    compose:
      enabled: false
  mongodb:
      uri: ${MONGODB_URI}

server:
  port: ${SERVER_PORT}
  
jwt:
  private_key: ${JWT_CLIENT_PRIVATE_KEY}
  public_key: ${JWT_CLIENT_PUBLIC_KEY}
  gateway_public_key: ${JWT_GATEWAY_PUBLIC_KEY}

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
