spring:
  application:
    name: core-logistic-finance-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: ${SERVER_PORT}

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}

jwt:
  gateway:
    public_key: ${JWT_GATEWAY_PUBLIC_KEY}