server:
  port: ${SERVER_PORT}

jwt:
  gateway:
    private_key: ${JWT_GATEWAY_PRIVATE_KEY}
    public_key: ${JWT_GATEWAY_PUBLIC_KEY}
    client_public_key: ${JWT_CLIENT_PUBLIC_KEY}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}