server:
  port: ${SERVER_PORT}


spring:
  application:
    name: ${SPRING_APPLICATION_NAME:api-gateway}
  cloud:
    gateway:
      server:
        webmvc:
          routes:
          - id: auth-service
            uri: lb://auth-service
            
            predicates:
              - Path=/auth/**
            filters:
              - AddRequestHeader=X-Gateway, Dynamic


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}