spring:
  application:
    name: ${SPRING_APPLICATION_NAME:api-gateway}
  profiles:
    active:
    - ${SPRING_PROFILES_ACTIVE:dev}
  cloud:
    gateway:
      server:
        webmvc:
          routes:
          - id: auth-service
            uri: lb://auth-service
            
            predicates:
              - Path=/api/auth/**
            filters:
              - AddRequestHeader=X-Gateway, Dynamic
          - id: user-branch-service
            uri: lb://user-branch-service
            predicates:
              - Path=/api/users/**,/api/branches/**
            filters:
              - AddRequestHeader=X-Gateway, Dynamic
          - id: inventory-service
            uri: lb://inventory-service
            predicates:
              - Path=/api/inventory/**
            filters:
              - AddRequestHeader=X-Gateway, Dynamic