/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BranchRouteImport } from './routes/branch'
import { Route as R404RouteImport } from './routes/404'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardShipmentsRouteImport } from './routes/dashboard/shipments'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardProfilesRouteImport } from './routes/dashboard/profiles'
import { Route as DashboardProductsRouteImport } from './routes/dashboard/products'
import { Route as DashboardPickupsRouteImport } from './routes/dashboard/pickups'
import { Route as DashboardInventoryRouteImport } from './routes/dashboard/inventory'
import { Route as DashboardBranchesRouteImport } from './routes/dashboard/branches'
import { Route as DashboardAccountsRouteImport } from './routes/dashboard/accounts'
import { Route as DashboardProfileProfileIdRouteImport } from './routes/dashboard/profile/$profileId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchRoute = BranchRouteImport.update({
  id: '/branch',
  path: '/branch',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardShipmentsRoute = DashboardShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfilesRoute = DashboardProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPickupsRoute = DashboardPickupsRouteImport.update({
  id: '/pickups',
  path: '/pickups',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInventoryRoute = DashboardInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBranchesRoute = DashboardBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountsRoute = DashboardAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileProfileIdRoute =
  DashboardProfileProfileIdRouteImport.update({
    id: '/profile/$profileId',
    path: '/profile/$profileId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/branch': typeof BranchRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/accounts': typeof DashboardAccountsRoute
  '/dashboard/branches': typeof DashboardBranchesRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/pickups': typeof DashboardPickupsRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/profiles': typeof DashboardProfilesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/shipments': typeof DashboardShipmentsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/profile/$profileId': typeof DashboardProfileProfileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/branch': typeof BranchRoute
  '/login': typeof LoginRoute
  '/dashboard/accounts': typeof DashboardAccountsRoute
  '/dashboard/branches': typeof DashboardBranchesRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/pickups': typeof DashboardPickupsRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/profiles': typeof DashboardProfilesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/shipments': typeof DashboardShipmentsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/profile/$profileId': typeof DashboardProfileProfileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/branch': typeof BranchRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/accounts': typeof DashboardAccountsRoute
  '/dashboard/branches': typeof DashboardBranchesRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/pickups': typeof DashboardPickupsRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/profiles': typeof DashboardProfilesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/shipments': typeof DashboardShipmentsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/profile/$profileId': typeof DashboardProfileProfileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/404'
    | '/branch'
    | '/dashboard'
    | '/login'
    | '/dashboard/accounts'
    | '/dashboard/branches'
    | '/dashboard/inventory'
    | '/dashboard/pickups'
    | '/dashboard/products'
    | '/dashboard/profiles'
    | '/dashboard/settings'
    | '/dashboard/shipments'
    | '/dashboard/'
    | '/dashboard/profile/$profileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/404'
    | '/branch'
    | '/login'
    | '/dashboard/accounts'
    | '/dashboard/branches'
    | '/dashboard/inventory'
    | '/dashboard/pickups'
    | '/dashboard/products'
    | '/dashboard/profiles'
    | '/dashboard/settings'
    | '/dashboard/shipments'
    | '/dashboard'
    | '/dashboard/profile/$profileId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/404'
    | '/branch'
    | '/dashboard'
    | '/login'
    | '/dashboard/accounts'
    | '/dashboard/branches'
    | '/dashboard/inventory'
    | '/dashboard/pickups'
    | '/dashboard/products'
    | '/dashboard/profiles'
    | '/dashboard/settings'
    | '/dashboard/shipments'
    | '/dashboard/'
    | '/dashboard/profile/$profileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  R404Route: typeof R404Route
  BranchRoute: typeof BranchRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch': {
      id: '/branch'
      path: '/branch'
      fullPath: '/branch'
      preLoaderRoute: typeof BranchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/shipments': {
      id: '/dashboard/shipments'
      path: '/shipments'
      fullPath: '/dashboard/shipments'
      preLoaderRoute: typeof DashboardShipmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profiles': {
      id: '/dashboard/profiles'
      path: '/profiles'
      fullPath: '/dashboard/profiles'
      preLoaderRoute: typeof DashboardProfilesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pickups': {
      id: '/dashboard/pickups'
      path: '/pickups'
      fullPath: '/dashboard/pickups'
      preLoaderRoute: typeof DashboardPickupsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory': {
      id: '/dashboard/inventory'
      path: '/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof DashboardInventoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/branches': {
      id: '/dashboard/branches'
      path: '/branches'
      fullPath: '/dashboard/branches'
      preLoaderRoute: typeof DashboardBranchesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/accounts': {
      id: '/dashboard/accounts'
      path: '/accounts'
      fullPath: '/dashboard/accounts'
      preLoaderRoute: typeof DashboardAccountsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile/$profileId': {
      id: '/dashboard/profile/$profileId'
      path: '/profile/$profileId'
      fullPath: '/dashboard/profile/$profileId'
      preLoaderRoute: typeof DashboardProfileProfileIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAccountsRoute: typeof DashboardAccountsRoute
  DashboardBranchesRoute: typeof DashboardBranchesRoute
  DashboardInventoryRoute: typeof DashboardInventoryRoute
  DashboardPickupsRoute: typeof DashboardPickupsRoute
  DashboardProductsRoute: typeof DashboardProductsRoute
  DashboardProfilesRoute: typeof DashboardProfilesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardShipmentsRoute: typeof DashboardShipmentsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProfileProfileIdRoute: typeof DashboardProfileProfileIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountsRoute: DashboardAccountsRoute,
  DashboardBranchesRoute: DashboardBranchesRoute,
  DashboardInventoryRoute: DashboardInventoryRoute,
  DashboardPickupsRoute: DashboardPickupsRoute,
  DashboardProductsRoute: DashboardProductsRoute,
  DashboardProfilesRoute: DashboardProfilesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardShipmentsRoute: DashboardShipmentsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProfileProfileIdRoute: DashboardProfileProfileIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  R404Route: R404Route,
  BranchRoute: BranchRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
