spring:
  application:
    name: support-and-notifications-service

  mongodb:
    uri: ${MONGODB_URI}

  jpa:
    hibernate:
      ddl-auto: update
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: ${SERVER_PORT}

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}

jwt:
  gateway:
    public-key-path: ${JWT_GATEWAY_PUBLIC_KEY_PATH}