spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gotrack2_db
    username: root
    password: root2552005
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true