spring:
  security:
    user:
      name: disabled
      password: disabled
  profiles:
    active:
    - ${SPRING_PROFILES_ACTIVE:dev}

server:
  shutdown: graceful

spring.lifecycle:
  timeout-per-shutdown-phase: 30s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${HOST_IP:localhost}
  client:
    healthcheck:
      enabled: true